### PR TITLE
Using graphite finder for events

### PR DESCRIPTION
**Pull request by goru97**
Renamed "garafana" to "grafana"
Using graphite-api to call blueflood for events.

### CODE REVIEW

**Comment by GeorgeJahad** [comment]
+1

**Comment by goru97** [comment]
I can't merge this PR. @rs-randallburt Can you?

**Comment by rs-randallburt** [comment]
I fixed the permissions @goru97. Try now.

**Comment by goru97** [comment]
@rs-randallburt Thanks very much

**Pull request merged**
